module.exports = {
  nursery: [
    { name: 'Numeracy', code: 'NUM' },
    { name: 'Literacy', code: 'LIT' },
    { name: 'Drawing', code: 'DRW' },
    { name: 'Rhymes', code: 'RHY' },
    { name: 'Coloring', code: 'CLR' },
    { name: 'Story Time', code: 'STO' },
  ],
  primary: [
    { name: 'Mathematics', code: 'MATH' },
    { name: 'English', code: 'ENG' },
    { name: 'Basic Science', code: 'BSC' },
    { name: 'Social Studies', code: 'SOC' },
    { name: 'Creative Arts', code: 'ART' },
    { name: 'Physical & Health Education', code: 'PHE' },
    { name: 'ICT', code: 'ICT' },
  ],
  secondary: [
    { name: 'Mathematics', code: 'MATH' },
    { name: 'English', code: 'ENG' },
    { name: 'Basic Science', code: 'BSC' },
    { name: 'Basic Technology', code: 'BTECH' },
    { name: 'Social Studies', code: 'SOC' },
    { name: 'Business Studies', code: 'BUS' },
    { name: 'Agricultural Science', code: 'AGR' },
    { name: 'Civic Education', code: 'CIV' },
    { name: 'ICT', code: 'ICT' },
    { name: 'Physics', code: 'PHY' },
    { name: 'Chemistry', code: 'CHEM' },
    { name: 'Biology', code: 'BIO' },
    { name: 'Further Mathematics', code: 'FMATH' },
    { name: 'Geography', code: 'GEO' },
    { name: 'Economics', code: 'ECO' },
    { name: 'Government', code: 'GOV' },
    { name: 'Literature', code: 'LIT' },
    { name: 'CRS/IRS', code: 'CRS' },
    { name: 'Commerce', code: 'COM' },
    { name: 'Accounting', code: 'ACC' },
  ],
};
